    open(1, file="MD_real.bin", access='stream', status='replace', form='unformatted')
    write(1) real(MD)
    close(1)    
    open(1, file="MD_imag.bin", access='stream', status='replace', form='unformatted')
    write(1) imag(MD)
    close(1)
    
    open(1, file="b_real.bin", access='stream', status='replace', form='unformatted')
    write(1) real(b)
    close(1)    
    open(1, file="b_imag.bin", access='stream', status='replace', form='unformatted')
    write(1) imag(b)
    close(1)
    
    open(1, file="ODp1_real.bin", access='stream', status='replace', form='unformatted')
    write(1) real(ODp1)
    close(1)    
    open(1, file="ODp1_imag.bin", access='stream', status='replace', form='unformatted')
    write(1) imag(ODp1)
    close(1)
    
    open(1, file="ODp2_real.bin", access='stream', status='replace', form='unformatted')
    write(1) real(ODp2)
    close(1)    
    open(1, file="ODp2_imag.bin", access='stream', status='replace', form='unformatted')
    write(1) imag(ODp2)
    close(1)
    
    open(1, file="ODp3_real.bin", access='stream', status='replace', form='unformatted')
    write(1) real(ODp3)
    close(1)    
    open(1, file="ODp3_imag.bin", access='stream', status='replace', form='unformatted')
    write(1) imag(ODp3)
    close(1)
